# Generated by Django 4.1.3 on 2022-12-13 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blockcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockcomment',
            old_name='sno',
            new_name='son',
        ),
    ]
