# Generated by Django 4.1.3 on 2022-12-13 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_sno_blockcomment_son'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockcomment',
            old_name='son',
            new_name='sno',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='son',
            new_name='sno',
        ),
    ]
