# Generated by Django 4.1.3 on 2023-01-11 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
    ]
