# Generated by Django 4.1.3 on 2023-01-06 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_myproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyProject',
        ),
    ]
