# Generated by Django 4.1.3 on 2023-01-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_myproject_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='img',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
