# Generated by Django 4.1.3 on 2023-01-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_myproject_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='img',
            field=models.ImageField(default='', upload_to='Users/LENOVO/Downloads'),
        ),
    ]
