# Generated by Django 4.1.3 on 2023-01-07 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_myproject_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myproject',
            name='img',
        ),
    ]
