# Generated by Django 4.1.3 on 2023-01-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_myproject_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproject',
            name='img',
            field=models.ImageField(default='', upload_to='static/img'),
        ),
    ]
