# Generated by Django 4.1.3 on 2023-01-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_myproject_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproject',
            name='bag',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
