# Generated by Django 4.1.3 on 2023-01-10 22:56

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_myproject_bag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
