# Generated by Django 4.1.3 on 2023-01-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_myproject_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='content',
            field=models.TextField(),
        ),
    ]
